stages:
  filter-tracklist:
    cmd: python src/filter_tracklist.py
    deps:
    - data/fma_metadata/
    - data/fma_small
    - src/filter_tracklist.py
    outs:
    - out/tracks_small.csv
  clean-up-tracklist:
    cmd: python src/clean_up_genre.py
    deps:
    - out/tracks_small.csv
    - data/fma_metadata/
    - src/clean_up_genre.py
