stages:
  filter-tracklist:
    cmd: python src/filter_tracklist.py
    deps:
    - data/raw/fma_metadata/
    - data/raw/fma_small
    - src/filter_tracklist.py
    outs:
    - data/processed/tracks_small.csv
  clean-up-tracklist:
    cmd: python src/clean_up_genre.py
    deps:
    - data/processed/tracks_small.csv
    - data/raw/fma_metadata/
    - src/clean_up_genre.py
    outs:
    - data/processed/clean_tracks_small.csv
  split-data:
    cmd: python src/split_data.py
    params:
      - test_set_size
      - valid_set_size
    deps:
    - data/processed/clean_tracks_small.csv
    - src/split_data.py
    outs:
    - data/final/testing_set.csv
    - data/final/training_set.csv
    - data/final/validation_set.csv
  train model:
    cmd: python -m src.train
    params:
      - batch_size
      - num_workers
      - learning_rate
      - max_epochs
    deps:
      - src/train.py
      - src/model.py
      - src/dataset.py
      - data/final/training_set.csv
      - data/final/validation_set.csv
      - data/raw/fma_small/
    outs:
      - models/model.pt
      - logs/training/version_0/
    metrics:
      - data/final/metrics.json
